# meu-ecommerce-monorepo/docker-compose.yml

version: '3.8'

services:
  #####################################
  # BANCO DE DADOS DO SERVIÇO DE CATÁLOGO E PAGAMENTOS
  #####################################
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db-ecommerce
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  #####################################
  # CACHE DO SERVIÇO DE CARRINHO
  #####################################
  redis-cache:
    image: redis:7-alpine
    container_name: redis-cache-ecommerce
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - ecommerce-network

  #####################################
  # MESSAGE BROKER PARA EVENTOS
  #####################################
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq-ecommerce
    ports:
      - "${RABBITMQ_PORT}:5672"       # Porta para a aplicação se conectar
      - "${RABBITMQ_MANAGE_PORT}:15672" # Porta para a interface de gerenciamento web
    networks:
      - ecommerce-network

volumes:
  postgres_data:
    driver: local

networks:
  ecommerce-network:
    driver: bridge